import Navbar from "@/components/navbar";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="flex flex-col justify-center items-center w-full mt-[100px]">
          {children}
        </main>
      </body>
    </html>
  );
}
